# arxiv/zero-worker

FROM arxiv/base:latest

ADD requirements/prod.txt /opt/arxiv/requirements.txt
RUN pip install -U pip && pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

ADD zero/ /opt/arxiv/zero/

WORKDIR /opt/arxiv/
ENTRYPOINT ["celery", "worker"]
CMD ["-A", "zero.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=4"]
